<?php

namespace Mallapp\SimpleauthBundle\Repository;

/**
 * BaseUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseUserRepository extends \Doctrine\ORM\EntityRepository
{
}
